export const REQUESTS_LIST_REQUEST = "REQUEST_LIST_REQUEST ";
export const REQUESTS_LIST_SUCCESS = "REQUEST_LIST_SUCCESS";
export const REQUESTS_LIST_FAIL = "REQUEST_LIST_FAIL";

export const REQUESTS_CREATE_REQUEST = "REQUEST_CREATE_REQUEST ";
export const REQUESTS_CREATE_SUCCESS = "REQUEST_CREATE_SUCCESS";
export const REQUESTS_CREATE_FAIL = "REQUEST_CREATE_FAIL";

export const REQUESTS_UPDATE_REQUEST = "REQUEST_UPDATE_REQUEST ";
export const REQUESTS_UPDATE_SUCCESS = "REQUEST_UPDATE_SUCCESS";
export const REQUESTS_UPDATE_FAIL = "REQUEST_UPDATE_FAIL";

export const REQUESTS_DELETE_REQUEST = "REQUEST_DELETE_REQUEST ";
export const REQUESTS_DELETE_SUCCESS = "REQUEST_DELETE_SUCCESS";
export const REQUESTS_DELETE_FAIL = "REQUEST_DELETE_FAIL";
